db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: dont_use_root_user
    MYSQL_USER: drupal
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: drupal
php:
  image: php-fpm-drupal
  command: /opt/start_php_fpm.sh
  links:
    - db
#  volumes:
#    - custom_libraries/custom-library-here:/srv/http/drupal/sites/all/libraries/custom-library-here
nginx:
  image: nginx-drupal
  links:
    - php
  command: /opt/start_nginx.sh
  ports:
    - "80:80"
    - "443:443"
#  volumes:
#    - custom_libraries/custom-library-here:/srv/http/drupal/sites/all/libraries/custom-library-here
