FROM dmp1ce/php-fpm-drupal
MAINTAINER David Parrish <daveparrish@gmail.com>

COPY drupal.make.yml /srv/http/drupal/drupal.make.yml
RUN drush make -y --contrib-destination=sites/all/modules/contrib --prepare-install /srv/http/drupal/drupal.make.yml
COPY php/settings.php /srv/http/drupal/sites/default/settings.php
# Copy custom modules.
COPY custom_contrib_modules /srv/http/drupal/sites/all/modules/custom_contrib
# Copy custom libraries.
#COPY custom_libraries/custom-library-here /srv/http/drupal/sites/all/libraries/custom-library-here
