FROM nginx:latest
MAINTAINER David Parrish <daveparrish@gmail.com>

COPY nginx/nginx.conf /etc/nginx/nginx.conf
#COPY nginx/htpasswd /etc/nginx/htpasswd
COPY nginx/start_nginx.sh /opt/start_nginx.sh
COPY nginx/drupal /srv/http/drupal
COPY nginx/ssl /usr/local/ssl
